server:
  port: 8399

spring:
  liquibase:
    user: postgres
    password: makintosh1380
    change-log: 'classpath:db-migrations/changelog.xml'
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=public"
    username: postgres
    password: makintosh1380

internal:
  cars:
    max-year: ${INTERNAL_CARS_MAX_YEAR:10}
    offset: ${INTERNAL_CARS_OFFSET:5}